export const FONT_NAMES = [
  'Alder Wake',
  'Ashenmere',
  'Autumn Hart',
  'Barrowfen',
  'Beetlewick',
  'Blackthorn',
  'Boglight',
  'Bramblemere',
  'Branthold',
  'Briar Hare',
  'Briar Wake',
  'Briar Witch',
  'Burdock Hollow',
  'Caelith',
  'Cinderholt',
  'Cloudberry',
  'Cloverweir',
  'Coldspark',
  'Copperfen',
  'Corvidale',
  'Cricketholt',
  'Crow Sister',
  'Crowfen',
  'Dapplefen',
  'Deadnettle',
  'Dewmere',
  'Dunhollow',
  'Dusk Herald',
  'Duskweir',
  'Eelweir',
  'Elderfen',
  'Emberweir',
  'Faelorn',
  'Fallowmere',
  'Fennelwick',
  'Fernholt',
  'Feverfew',
  'Fieldwisp',
  'Finchhollow',
  'Firethorn',
  'Fogwillow',
  'Fox Wife',
  'Foxfire',
  'Foxfire Hollow',
  'Frost Knave',
  'Frostmere',
  'Glenwold',
  'Glimmerfen',
  'Goatwillow',
  'Goldengorse',
  'Gorse Witch',
  'Gorsefall',
  'Gravemoss',
  'Greenwight',
  'Greymoor',
  'Gwyndle',
  'Hagfen',
  'Hare Queen',
  'Harebell',
  'Hartwood',
  'Hawthorn',
  'Hearth Knave',
  'Heatherwick',
  'Hedgewise',
  'Heronmere',
  'Hobhollow',
  'Hollow Crown',
  'Hollowmere',
  'Hollyweir',
  'Icemoss',
  'Ironweir',
  'Ivy Warden',
  'Juniper Hollow',
  'Kelpfell',
  'Kestrelmere',
  'Kingfisher',
  'Knotgrass',
  'Ladyfern',
  'Lanternmoss',
  'Lark Thief',
  'Larkspire',
  'Lichenfall',
  'Linnetfen',
  'Lostweir',
  'Mallowfen',
  'Marshlight',
  'Meadowrue',
  'Midwinter',
  'Milkweed',
  'Mistwold',
  'Mistleholt',
  'Moon Warden',
  'Moonwake',
  'Moonwort',
  'Moorwake',
  'Moss Wife',
  'Moth Sister',
  'Mugwort',
  'Myrwood',
  'Nettlebrook',
  'Nightbloom',
  'Nightjar',
  'Oakshade',
  'Oldbriar',
  'Otterweir',
  'Owl Keeper',
  'Pale Hart',
  'Pebblefen',
  'Pike Wife',
  'Pinehollow',
  'Puckhollow',
  'Quillfen',
  'Ragwort',
  'Ravenholt',
  'Ravenscar',
  'Redcap',
  'Reedmere',
  'Riverwisp',
  'Rook Warden',
  'Rowanfen',
  'Ruehollow',
  'Russetmoor',
  'Sagehollow',
  'Saltmere',
  'Selfheal',
  'Silverfen',
  'Sloe Witch',
  'Sloethorn',
  'Sorrelweir',
  'Sparrowfen',
  'Speedwell',
  'Spindlewood',
  'Stagfall',
  'Stitchwort',
  'Stoat Knave',
  'Stonehollow',
  'Tangleweir',
  'Tansyfield',
  'Teasel',
  'Thistlewick',
  'Thorn Knave',
  'Thornmere',
  'Thornwick',
  'Toadfen',
  'Toadflax',
  'Tormentil',
  'Umberholt',
  'Valehart',
  'Valerian',
  'Vervain',
  'Vixenmere',
  'Waybread',
  'Wickerfen',
  'Wildermoss',
  'Willowmere',
  'Windholt',
  'Witchhazel',
  'Woldmere',
  'Woodruff',
  'Wormwood',
  'Wren Thief',
  'Wyrd Hollow',
  'Yarrowfen',
  'Yewshade',
] as const;
